---
- name: Converge
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Verify cluster is working.
      k8s_info:
        namespace: kube-system
        kind: Pod
      register: pod_list
